data:
    dataset: "AFHQ"
    train_path: "./datasets/afhq_256/train"
    val_path: "./datasets/afhq_256/val"
    kernel_size: 55
    kernel_train_path: "./datasets/kernel/55_train.npz"
    kernel_val_path: "./datasets/kernel/55_val.npz"
    netG_path: "./models/netG_55.pth"
    netE_path: "./models/netE_55.pth"
    save_path: "./models"

task_config:
    seed: 0
    num_epochs: 60
    num_iters: 100
    lr: 0.001 #0.0001
    lr_z: 0.01 #0.01
    batch_size: 1280 #128
    weight_lambda: 0.1